name: hallobet
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  carousel_slider: ^4.2.1
  csv: ^5.0.0
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  ml_algo: ^16.17.10
  ml_dataframe: ^1.6.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/dummy.json
    - assets/obesity_dataset.csv
    - assets/image/
    - assets/fonts/

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy/Gilroy-Regular.ttf
        - asset: assets/fonts/Gilroy/Gilroy-Medium.ttf
        - asset: assets/fonts/Gilroy/Gilroy-Bold.ttf

    - family: Righteous
      fonts:
        - asset: assets/fonts/Righteous/Righteous-Regular.ttf

    - family: Gotham
      fonts:
        - asset: assets/fonts/Gotham/GothamBold.ttf
